from django.contrib.auth import get_user_model
from django.test import TestCase

from temperature.models import Thermometer


class ThermometerModelTests(TestCase):
    """Tests for Thermometer Class

    Methods:
        test_auto_generate_id: Saving a model should auto-generate a uuid
        test_duplicate_id_rejeceted: UUIDs need to be unique, so attempting to re-use one
            should fail
        test_new_therm_no_owner: New thermometers should not need owners to be added to DB.
        test_new_therm_not_registered: New Thermometers should not be regestered

    References:
    """

    def setUp(self):
        """
        Create seed data for tests
        """
        self.user_model = get_user_model()
        self.user_model.objects.create_user(
            username="testy",
            password="pass",
            email="test@test.com"
        )

    def test_auto_generate_id(self):
        """
        New therms should have uuid autogenerated
        """
        therm = Thermometer(
            display_name="test thermometer"
        )
        therm.save()
        self.assertTrue(therm.therm_id)

    def test_uniqueness_of_ids(self):
        ids = set()
        for _ in range(1000000):
            therm = Thermometer()
            therm.save()
            self.assertFalse(therm.therm_id in ids)
            ids.add(therm.therm_id)

